name: Security Scan

on:
  pull_request:
    branches: [main]

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-slim
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semgrep:
    name: semgrep
    runs-on: ubuntu-slim
    if: github.actor != 'dependabot[bot]'
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: semgrep scan --config=auto --error
